[tox]
toxworkdir={toxinidir}/.tox_{env:Python}


[testenv]
runner = uv-venv-runner
pass_env =
    WORKSPACE
    HOME
setenv =
    CXX = g++
    CC = gcc
    UV_PROJECT_ENVIRONMENT = {toxinidir}/.tox_{env:Python}/py
    PYTHONPATH = {toxinidir}
changedir = {toxworkdir}
ignore_outcome = True
ignore_errors = True
allowlist_externals =
    /bin/bash
    uv
with_dev = True
extras =
    filemagic
    regex
dependency_groups =
    dev
    test

commands =
    coverage run --source eml_parser -m pytest -v --junitxml={toxinidir}/junit_{env:Python}.xml {toxinidir}/tests
    coverage xml -o {toxinidir}/coverage_{env:Python}.xml

    /bin/bash -c 'mypy --config-file {toxinidir}/pyproject.toml {toxinidir}/eml_parser > {toxinidir}/mypy_{env:Python}.log'

    ruff check --config {toxinidir}/pyproject.toml --output-format pylint --output-file {toxinidir}/pylint_{env:Python}.log {toxinidir}/eml_parser
